# Generated by Django 4.2.5 on 2023-09-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_letter', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Lenguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguages', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitles', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TipeMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(default='movies/static/movies/images/', upload_to='image')),
                ('first_name_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_letters', to='movies.firstletter')),
                ('movies_lenguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenguage', to='movies.lenguage')),
                ('movies_subtitles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle', to='movies.subtitle')),
                ('movies_tipe_movie', models.ManyToManyField(blank=True, related_name='movies_tipe', to='movies.tipemovie')),
                ('movies_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year', to='movies.year')),
            ],
        ),
    ]
