# Generated by Django 4.2.5 on 2023-09-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='movies/static/movies/images/', upload_to='movies/static/movies/image'),
        ),
    ]
